### ISSUE TITLE
Support `XDG Base Directory` spec for retrieve bookmarks 

### ISSUE THREAD

**Issue by erayaydin** [dhruvmanila/browser-bookmarks.nvim#16]
Currently, bookmarks extension finding bookmarks databases with hardcoded `.config/**` directory ([example](https://github.com/dhruvmanila/telescope-bookmarks.nvim/blob/main/lua/telescope/_extensions/bookmarks/chrome.lua#L53)). Some users use different path for storing configuration files. In the plugin, I suggest change hardcoded `.config` strings with `os.getenv('XDG_CONFIG_HOME') or '.config'`.

As another method (or in addition to the above); users can describe bookmark path in the telescope's extension configurations. Example;

```
telescope.setup({
  ...
  extensions = {
    bookmarks = {
      chrome = "custom path depends on user's environment",
    },
  },
})
```

More information about XDG Base Directory spec [here](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

**Comment by erayaydin** [comment]
> Can you tell me a use case for this?

Some users start browsers in separate environments. For example; `~/.config/qutebrowser/personal` for daily usage and `~/.config/qutebrowser/work` for working environment. It's also happening for other browsers (chromium, firefox, etc.) via correct wrappers.

For this, if other users specify here or react, then it's can be added. For now, we can skip this feature until enough requests.

> So, if you want, you can proceed with https://github.com/dhruvmanila/telescope-bookmarks.nvim/issues/15 before working on this.

I'll try implementation about #15 over the weekend.

**Comment by dhruvmanila** [comment]
Hi @erayaydin, so I've made the changes required to support `XDG_CONFIG_HOME` which is what is mainly used but there are some inconsistencies. Only the chromium based browsers which includes brave, chrome, edge, and vivaldi are supported. In other browsers, the base directory does not follow the XDG spec in one or more operation systems.

**Comment by dhruvmanila** [comment]
Hi @erayaydin Is this actually required now that #30 is merged ?

**Comment by dhruvmanila** [comment]
I'm closing this issue as this feature is not necessarily required.

You can specify custom path to the browser directory using the config option [`config_dir`](https://github.com/dhruvmanila/browser-bookmarks.nvim#config_dir-string-default-nil).
