### ISSUE TITLE
Add Support for Raindrop.io

### ISSUE THREAD

**Issue by CharlesARoy** [dhruvmanila/browser-bookmarks.nvim#21]
I use the Raindrop.io bookmark manager which is far more powerful than any browser-based bookmark manager I've tried. Plus, since it's in the cloud, it works across browsers.

Would it be possible to support Raindrop.io in the future?

Here's [a link to the feature request](https://better.raindrop.io/feature-requests/p/add-support-for-neovims-telescope-bookmarks-extension) I made for this in Raindrop.io. The author of Raindrop.io (Rustem Mussabekov) is very responsive if you reach out to him at info@raindrop.io.

**Comment by dhruvmanila** [comment]
Hi, thanks for the feature request.

I went through their API docs and it seems there's only one way to get the access token which is to go through the OAuth flow which is not possible for the extension. The other way is to have the user provide his/her test token which I don't suppose is safe (or is it?). An argument could be made that the user is provided the token on his/her behalf to allow the extension to access his/her bookmarks.

I've mailed the author with the same details and asking if there's any way to make this feature available. I'll keep you posted regarding my conversation.

**Comment by Darqon96** [comment]
Hi @dhruvmanila, 
any news regarding this feature? 

I'm using Raindrop.io too and I think that it would be great for anyone using Raindrop.io to have this feature in telescope :telescope:

Please make it happen :pray:

**Comment by dhruvmanila** [comment]
Hi, sorry for the delay. I got the response from the creator of raindrop.io and it'll be similar to how the [Raycast extension](https://www.raycast.com/lardissone/raindrop-io) have been developed. There'll be a new config option `raindrop_token` which will be the test token for the user and it'll be used to fetch the bookmarks data from their API. Currently, I'm not thinking of fetching the entire path to the bookmark where the path would include all the collections which leads to this bookmark.

**Comment by dhruvmanila** [comment]
Hi @Darqon96 @CharlesARoy, can anyone try the `feat/raindrop` branch? Currently, it's synchronous so the editor will freeze until the API responds. I'm debating if it's worth making it asynchronous.

**Comment by dhruvmanila** [comment]
There's one problem which is that currently the access token is taken from the config, but as most of the dotfiles are public, that exposes the said user's access token which is a security risk. I need to think as in how to get the user token without putting it in the user config. Any ideas would be appreciated!

**Comment by Darqon96** [comment]
> Hi @Darqon96 @CharlesARoy, can anyone try the `feat/raindrop` branch? Currently, it's synchronous so the editor will freeze until the API responds. I'm debating if it's worth making it asynchronous.

Hi @dhruvmanila,

Sadly, I can't get it to work. 

I have copied `Test token` from Raindrop.io and added it to configuration under `raindrop_token`, but when I execute `:Telescope bookmarks` command it shows `Search Brave Bookmarks` in the title and bookmarks from Raindrop.io can't be seen

**Comment by CharlesARoy** [comment]
> Hi @Darqon96 @CharlesARoy, can anyone try the `feat/raindrop` branch? Currently, it's synchronous so the editor will freeze until the API responds. I'm debating if it's worth making it asynchronous.

Hi @dhruvmanila,

Sorry for the delay. I was partially able to get it to work (on the 2nd try!) but still have a few issues.

First, here's what the telescope-bookmarks extension config looks like in my telescope config:
![image](https://user-images.githubusercontent.com/46253001/209258582-82822149-53cf-4f99-8748-90ce9d6f8e28.png)

Note, it only worked when I set the selected_browser to 'raindrop' which wasn't listed as one of the available options (maybe that's where @Darqon96 got hung up). That does raise the issue of how to open Raindrop.io links in the desired browser though.

Now if I run this command `:lua require('telescope').extensions.bookmarks.bookmarks(opts)`, I see this popup:
![image](https://user-images.githubusercontent.com/46253001/209259082-8cd52a69-c936-4984-acf6-1cb7ee673fb0.png)

What's odd is that I'm only seeing the first 17 results from the Unsorted folder in Raindrop.io and no links from any of my other folders.
![image](https://user-images.githubusercontent.com/46253001/209259209-6abb0e39-2893-4cbe-8303-fa39115693dd.png)

The last issue is that if I select a link, I get the following error:
`open-browser doesn't know how to open 'https://www.biostarhandbook.com/filtering-information-in-vcf-files.html'.`
This is probably because I'm running Neovim on a remote server via ssh and open-browser doesn't know how to tell my local system to launch Chrome... Not sure if you have any suggestions for that scenario. A partial solution is that in the Windows Terminal, I can Ctrl+Click a link and it will open in my default browser. However, some of the longer links get cut off by the window and if I click on them, they launch Chrome with only the visible part of the URL. Is there a way to ensure that the full URL is displayed in the Telescope window?
![image](https://user-images.githubusercontent.com/46253001/209260076-ec4cacef-8334-40b5-bb49-f29106313758.png)

**Comment by dhruvmanila** [comment]
Hi @CharlesARoy thanks for a detailed analysis.

> First, here's what the telescope-bookmarks extension config looks like in my telescope config:

It's unsafe to provide the token on a public forum, please reset the token.

> Note, it only worked when I set the selected_browser to 'raindrop' which wasn't listed as one of the available options

I've added it in the README and available options

> What's odd is that I'm only seeing the first 17 results from the Unsorted folder in Raindrop.io and no links from any of my other folders.

This should be fixed. It turns out that a max of 50 raindrops can be fetched at a time, so need to paginate the response. Although, this means that the editor will be frozen for a longer period of time to fetch all of the bookmarks.

> This is probably because I'm running Neovim on a remote server via ssh and open-browser doesn't know how to tell my local system to launch Chrome... Not sure if you have any suggestions for that scenario.

I'm not sure how to do it but maybe you could provide a command in `url_open_command` which could open the URL on your local system.

> Is there a way to ensure that the full URL is displayed in the Telescope window?

The best way would be to zoom out as the rendering is done by the core of Telescope. The extension has no control of it.

**Comment by CharlesARoy** [comment]
Hi @dhruvmanila thanks for the update and input!

> It's unsafe to provide the token on a public forum, please reset the token.

Not to worry, the above is just a dummy token to illustrate my setup.

> This should be fixed. It turns out that a max of 50 raindrops can be fetched at a time, so need to paginate the response. Although, this means that the editor will be frozen for a longer period of time to fetch all of the bookmarks.

I updated to the latest commit on the feat/raindrop branch but I'm still only getting the 17 most recent Unsorted bookmarks. Let me know if you need any more information for troubleshooting.

> The best way would be to zoom out as the rendering is done by the core of Telescope. The extension has no control of it.

Thanks for that suggestion, that works for me :)

**Comment by dhruvmanila** [comment]
Hi @CharlesARoy, I'm unable to figure out why would the bookmarks not show up on your end as I'm getting every bookmark from my end. My structure looks something like this:

<img width="298" alt="Screenshot 2023-01-14 at 10 39 32" src="https://user-images.githubusercontent.com/67177269/212456962-e8920649-b66d-4e20-921f-9b3cdc42d776.png">

What you could do is, using `curl`, Postman or anything similar to that, test out the request and see what you're getting:
* API URL: https://api.raindrop.io/rest/v1/raindrops/0
* Parameters: `{ "perpage": 50, "page": 0 }` (increment the page value until the `items` value is an empty list)

Another thing you could provide is the value of `count` in the response. This tells you the number of total items available.

This is what I'm doing in the code as well:

https://github.com/dhruvmanila/telescope-bookmarks.nvim/blob/582d4d4fc194f597ebf8961e26d51e67baf41323/lua/telescope/_extensions/bookmarks/raindrop.lua#L24-L34

**Comment by CharlesARoy** [comment]
Well, after waiting for a while and then trying it again, it seems to work now 🤷‍♂️

The only remaining issue (for me) is that it freezes for about a minute and a half to load my 4000+ bookmarks. @dhruvmanila were you still thinking of working on the asynchronous loading?

**Comment by dhruvmanila** [comment]
> were you still thinking of working on the asynchronous loading?

So, what I thought of is to do the asynchronous, but as you can see your response time is around 90 seconds. So, the editor won't be frozen but the telescope window will popup after a while which kind of defeats the purpose of the plugin as you could do the same from raindrop in less time.

What I'm thinking now is to run a background job when the plugin is loaded, caching the bookmarks. This could be a Time-To-Live cache whose value can be configured. Once, the cache is invalid due to timeout, a new job will be triggered. In addition to that, a command could be provided to invalidate the cache right then and trigger a new background job. Now, while the job is going on, if a user tries to open the telescope window, a notification could be provided stating something along the lines of "Bookmarks collection not available yet, please try again later".

**Comment by CharlesARoy** [comment]
@dhruvmanila running a background job to cache the bookmarks sounds awesome to me! I think that that would solve this "issue" for 99% of use cases.

**Comment by dhruvmanila** [comment]
Hi @CharlesARoy @Darqon96 can you try the `feat/raindrop` branch again. **There were some major changes which required force pushes on that branch so make sure to pull all the changes.**

Now, there's no `raindrop_token` config option. The plugin will ask for the token at first and then store it in a file at this path:

```lua
vim.fn.stdpath('state') .. '/.raindrop-token'
```

For every Neovim session, when you ask for Raindrop bookmarks (`BrowserBookmarks raindrop`), it will first start a background job to collect them. If you then ask again while the plugin is collecting the bookmarks, it will inform you with an appropriate message. Then, for the current Neovim session, the bookmarks will be cached and every subsequent invocation will be instant. The cache can be cleared using:

```lua
require("browser_bookmarks.browsers.raindrop").clear_cache()
```

For `clear_cache`, I'm thinking of starting the background job again right after the cache is cleared. What do you think?

**Comment by CharlesARoy** [comment]
Very delayed but just wanted to mention that it works amazingly @dhruvmanila ! Thanks so much for all your work on this!!

**Comment by dhruvmanila** [comment]
> Very delayed but just wanted to mention that it works amazingly @dhruvmanila ! Thanks so much for all your work on this!!

No problem at all! I'm glad it works well and thanks for the kind words :)
