### ISSUE TITLE
Add support for Arc Browser

### ISSUE THREAD

**Issue by audigregorie** [dhruvmanila/browser-bookmarks.nvim#35]
Hello,
Are you all planning to add compatibility to the Arc Browser?

Thank you for your hard work with the browser-bookmark!

**Comment by dhruvmanila** [comment]
Hey, thanks for using the extension!

Yes, I worked on a bit a while ago, I'll probably finish it in a few days and release it!

**Comment by dhruvmanila** [comment]
Actually, the branch was already ready, just needed some testing. I've pushed it, will make a release tag soon.

Closed by 309cbf2cdb9ec04551553acd3dcd759d9e9f3840

**Comment by audigregorie** [comment]
Excellent. Thank you @dhruvmanila
