### ISSUE TITLE
Artefact remains after opening a bookmark

### ISSUE THREAD

**Issue by pmatulis** [dhruvmanila/browser-bookmarks.nvim#36]
Artefact remains after opening a bookmark (in Google Chrome at least):

![image](https://github.com/dhruvmanila/browser-bookmarks.nvim/assets/6303808/65c328ad-bb07-4e05-9a36-f587c93b9c50)

Scrolling away fixes it.

**Comment by dhruvmanila** [comment]
Hi, I don't think that's related to this plugin. Whichever option you're using from either [`url_open_command`](https://github.com/dhruvmanila/browser-bookmarks.nvim#url_open_command) or [`url_open_plugin`](https://github.com/dhruvmanila/browser-bookmarks.nvim#url_open_plugin), either of them must be emitting the message and a probable bug in Neovim might be causing it to be displayed here.

Closing this issue but feel free to ask any other questions.
